openapi: 3.1.0
info:
  title: Lieu API
  version: 1.0.0
servers:
  - url: 'http://localhost:8082'
    description: Exemple de serveur API pour les lieux
paths:
  /lieux:
    get:
      summary: Liste tous les lieux
      responses:
        '200':
          description: Une liste des lieux
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationList'
    post:
      summary: Crée un nouveau lieu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '201':
          description: Nouveau lieu créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'

  /lieux/{lieuId}:
    get:
      summary: Récupère un lieu par son ID
      parameters:
        - name: lieuId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Un lieu détaillé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
    put:
      summary: Met à jour un lieu
      parameters:
        - name: lieuId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '200':
          description: Lieu mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
    delete:
      summary: Supprime un lieu
      parameters:
        - name: lieuId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Lieu supprimé

components:
  schemas:
    Location:
      type: object
      required:
        - id
        - name
        - address
        - latitude
        - longitude
      properties:
        id:
          type: integer
          description: Identifiant unique du lieu.
        name:
          type: string
          description: Nom du lieu.
        address:
          type: string
          description: Adresse du lieu.

    LocationList:
      type: array
      items:
        $ref: '#/components/schemas/Location'
